#!/bin/bash
# 🚀 QUICK START - JuridiColombia Landing
# Este script te ayuda a navegar rápidamente por los materiales

echo "================================"
echo "🚀 JURIDICOLOMBIA - LANDING PACK"
echo "================================"
echo ""
echo "Bienvenido a los materiales de presentación de JuridiColombia"
echo ""
echo "📁 Archivos disponibles:"
echo ""
echo "1. 📋 INDEX.md              - Empieza aquí (índice y navegación)"
echo "2. 🎯 OVERVIEW.md           - Resumen de todo lo que hay"
echo "3. 📄 README.md             - Guía de uso de la carpeta"
echo "4. 🎬 SALES-NOTES.md        - Scripts de ventas listos"
echo "5. 📊 PRODUCT-DESCRIPTION.md - Descripción completa"
echo "6. 🌐 index.html            - Página web interactiva (abre en navegador)"
echo ""
echo "================================"
echo "⚡ ACCIONES RÁPIDAS"
echo "================================"
echo ""
echo "✅ Si necesitas...              → Abre..."
echo ""
echo "  Empezar desde cero            → INDEX.md"
echo "  Entender qué hay aquí         → OVERVIEW.md"
echo "  Presentar a un cliente        → index.html (en navegador)"
echo "  Vender/hacer pitch            → SALES-NOTES.md"
echo "  Entender el producto          → PRODUCT-DESCRIPTION.md"
echo "  Entrenar a tu equipo          → README.md + SALES-NOTES.md"
echo ""
echo "================================"
echo "🎯 DATOS CLAVE PARA RECORDAR"
echo "================================"
echo ""
echo "📈 32,665    = Artículos legales"
echo "⚡ 0ms       = Latencia de búsqueda"
echo "💾 3.6 MB    = Tamaño de extensión"
echo "👥 150,000+  = Abogados en mercado"
echo "🔒 Cero      = Servidores/Tracking"
echo ""
echo "================================"
echo "📞 PRÓXIMO PASO"
echo "================================"
echo ""
echo "Abre: INDEX.md"
echo "Lee: La sección 'Ruta Rápida por Caso de Uso'"
echo "Selecciona: Tu caso (vendedor, inversor, etc.)"
echo "Comienza: Con los archivos recomendados"
echo ""
echo "¡Listo para vender!"
echo ""
